apiVersion: v1
kind: List
items:

- kind: DeploymentConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: spring-boot
    name: spring-boot-java
  spec:
    replicas: 1
    
    selector:
      app: spring-boot-java
      deploymentconfig: spring-boot-java
    strategy:
      resources: {}
    
    template:
      metadata:
        labels:
          app: spring-boot-java
          deploymentconfig: spring-boot-java
      
      spec:
        containers:
          - env:
            #- name: JAVA_APP_JAR
            #  value: spring-boot-bootified.war

            image: spring-boot-java:latest
            imagePullPolicy: Always
            name: spring-boot-java
            
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
    
    test: false
    
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot-java
        from:
          kind: ImageStreamTag
          name: spring-boot-java:latest
      type: ImageChange

- kind: Service
  apiVersion: 'v1'
  metadata:
    labels:
      app: spring-boot-java
    name: spring-boot-java
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-java
      deploymentconfig: spring-boot-java
  status:
    loadBalancer: {}

- kind: Route
  apiVersion: "v1"
  metadata:
    name: 'example'
    annotations:
      kubernetes.io/tls-acme: "true"
  spec:
    to:
      kind: Service
      name: 'spring-boot-java'
    port:
      targetPort: web